### ISSUE TITLE
Not working with Big Sur installer

### ISSUE THREAD

**Issue by tempelmann** [ITzTravelInTime/TINU#16]
I tried to use TINU (60) with the Big Sur Beta 1 installer app - it tells me that this is not a proper installer and can't use it.

And note that the BS installer will need 11 GB of disk space.

**Comment by ITzTravelInTime** [comment]
Hi, this has been fixed in the betas for version 3.0, orecisely the beta 3 added support for big sur, you can get it here: 

https://github.com/ITzTravelInTime/TINU/releases/tag/3.0_BETA_3_(70)

due to a known bug (caused by some file attribute issue) i reccomend you dragging the app to you desktop before opening it for the first time

**Comment by tempelmann** [comment]
Thanks. Please close this only once the release is out, so that users still see the issue here (with the solution) if they're using the current release, like me.

**Comment by tempelmann** [comment]
Ah, now I realize why I could not see the beta: The main page only lists the 2.1 release - one has to click the "+ 9 releases" button below to see the beta. I had expected to find only _older_ ones there, so I didn't bother to check. Maybe you could just add a small note on the main page's readme about the Big Sur beta? And then close this.

**Comment by ITzTravelInTime** [comment]
yes, i will need just some time to finish work on the new beta and the  pubblish it

**Comment by ITzTravelInTime** [comment]
> That known bug: It's not translocation? Quarantine perhaps? Email me if you need help with it. Always happy to help.

Forgot to say that the known bug is about adding the executable attribute to an internal .sh file, in order to be able to create installers  on system with SIP enabled from catalina onwrds, tinu needs to be launched from the terminal because the terminal is the only application to have really all the permitions needed by createinstallmedia when SIP is on

**Comment by ITzTravelInTime** [comment]
all of this stuff has been addressed in the latest release: https://github.com/ITzTravelInTime/TINU/releases/tag/3.0_BETA_4_(82)

**Comment by ITzTravelInTime** [comment]
I am closing this issue since the latest version is now no longer marked as a pre-release, this was done just to make sure people will download an updated version.
